FROM cirss/repro-parent:latest

ARG PARENT_BUILD_ARG_1
ENV PYTHON_VERSION=${PARENT_BUILD_ARG_1}

# install dependencies for building python 3.x
RUN apt-get update; 													\
	apt-get install -y build-essential gdb lcov pkg-config	 			\
    	libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev 	\
    	libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev 			\
    	lzma lzma-dev tk-dev uuid-dev zlib1g-dev

RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz ; \
	tar -xf Python-${PYTHON_VERSION}.tgz ; \
	cd Python-${PYTHON_VERSION}/ ; \
	./configure --enable-optimizations ; \
	make -j 4 ; \
	make install

RUN pip3 install --upgrade pip

